# This is a basic workflow to help you get started with Actions

name: Lighthouse Check

# Controls when the action will run. Triggers the workflow on push or pull request
# events 
on: 
  push: 
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  audit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Lighthouse Audit
        uses: jakejarvis/lighthouse-action@master
        with:
          url: 'https://speakher.jp/'
      - uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'
